version: '3.8'

services:

  blog_db:
    container_name: restoran_db
    image: postgres:15.1-alpine
    restart: always
    volumes:
      -  postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d restoran_m -U postgres" ]
      interval: 20s
      timeout: 5s
      retries: 5

  blog_app:
    container_name: blog_app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      sh -c "
        echo 'Starting my project' &&
        alembic upgrade head &
        uvicorn app:app --reload --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      restoran_db:
        condition: service_healthy
      restoran_redis:
        condition: service_healthy
    links:
      - blog_db
    restart: on-failure

volumes:
  postgres_data:
